Attempt to use image caches to speed up build

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -70,10 +70,10 @@ stages:
 #    - timeout --preserve-status 10s gunicorn --workers=1 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker baserow.config.asgi:application
 
 build-for-gitlab-project-registry:
-  image: docker:latest
+  image: docker:19.03.12
   stage: build
   services:
-    - docker:dind
+    - docker:19.03.12-dind
   variables:
     IMAGE_LABELS: >
       --label org.opencontainers.image.vendor=$CI_PROJECT_URL
@@ -91,6 +91,9 @@ build-for-gitlab-project-registry:
       --label com.gitlab.ci.commiturl=$CI_PROJECT_URL/commit/$CI_COMMIT_SHA
       --label com.gitlab.ci.cijoburl=$CI_JOB_URL
       --label com.gitlab.ci.mrurl=$CI_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_ID
+      # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
+      DOCKER_HOST: tcp://docker:2376
+      DOCKER_TLS_CERTDIR: "/certs"
   before_script:
     - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
   script:
@@ -134,7 +137,24 @@ build-for-gitlab-project-registry:
           done;
         fi
 
-        docker build --pull $FORMATTEDTAGLIST $IMAGE_LABELS_WITH_TITLE -f $IMAGE_PATH .;
+        # Try cache from this branches latest image, if not fall back to the latest
+        # develop image.
+        $CACHE_IMAGE=$IMAGE_REPO/$IMAGE_NAME:$LATEST_BRANCH_TAG
+        if ! docker pull $CACHE_IMAGE; then
+          CACHE_IMAGE=$IMAGE_REPO/$IMAGE_NAME:dev-latest;
+          if ! docker pull $CACHE_IMAGE; then
+             CACHE_IMAGE=""
+          fi
+        fi
+        if [[ -n "$CACHE_IMAGE" ]]; then
+          echo "Caching docker build from $CACHE_IMAGE"
+          CACHE_ARG="--cache-from $CACHE_IMAGE"
+        else
+          echo "Couldn't find image to cache build using"
+          CACHE_ARG=""
+        fi
+
+        docker build $CACHE_ARG $FORMATTEDTAGLIST $IMAGE_LABELS_WITH_TITLE -f $IMAGE_PATH .;
         if [[ -n "$ADDITIONALTAGLIST" ]]; then
           for TAG in $ADDITIONALTAGLIST; do
             docker push $IMAGE_REPO/$IMAGE_NAME:$TAG;
