Fix various issues

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -5,7 +5,7 @@ stages:
   - build
   - lint
   - test
-  - push
+  - publish
 #
 #web-frontend-eslint:
 #  stage: lint
@@ -69,10 +69,87 @@ stages:
 #    - python -c 'import baserow_premium'
 #    - export DJANGO_SETTINGS_MODULE='baserow.config.settings.base'
 #    - timeout --preserve-status 10s gunicorn --workers=1 -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker baserow.config.asgi:application
+variables:
+  CI_IMAGE_REPO: $CI_REGISTRY_IMAGE/ci
+  IMAGE_REPO: $CI_REGISTRY/testing
 
 build-baserow-images:
   image: docker:19.03.12
   stage: build
+  services:
+    - docker:19.03.12-dind
+  variables:
+    DOCKER_BUILDKIT: 1
+    DOCKER_HOST: tcp://docker:2376
+    DOCKER_TLS_CERTDIR: "/certs"
+  before_script:
+    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
+  script:
+    - |
+      build_and_push_ci_image(){
+        IMAGE_PATH=$1
+        IMAGE_NAME=$2
+
+        # Try cache from this branches latest image, if not fall back to the latest
+        # develop image.
+        # Ensure we don't go over 128 char docker tag length limit
+        TRUNCATED_BRANCH_NAME=${CI_COMMIT_REF_NAME:0:100}
+        BRANCH_TAG=$TRUNCATED_BRANCH_NAME-$CI_COMMIT_SHORT_SHA
+        DEV_LATEST_BRANCH_TAG=dev-$TRUNCATED_BRANCH_NAME-latest
+
+        CACHE_IMAGE="$IMAGE_REPO/$IMAGE_NAME:$DEV_LATEST_BRANCH_TAG"
+        if ! docker pull $CACHE_IMAGE; then
+          CACHE_IMAGE="$IMAGE_REPO/$IMAGE_NAME:dev-latest";
+          if ! docker pull $CACHE_IMAGE; then
+             CACHE_IMAGE=""
+          fi
+        fi
+
+        if [[ -n "$CACHE_IMAGE" ]]; then
+          echo "Caching docker build from $CACHE_IMAGE";
+          CACHE_ARG="--cache-from $CACHE_IMAGE";
+        else
+          echo "Couldn't find image to cache build using"
+          CACHE_ARG=""
+        fi
+
+        CI_IMAGE_PATH=$CI_IMAGE_REPO/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
+        docker build --build-arg BUILDKIT_INLINE_CACHE=1 $CACHE_ARG --target dev --tag $CI_IMAGE_PATH -f $IMAGE_PATH .;
+        docker push $CI_IMAGE_PATH
+      }
+
+      build_and_push_ci_image "$CI_PROJECT_DIR/backend/Dockerfile" "backend"
+      build_and_push_ci_image "$CI_PROJECT_DIR/web-frontend/Dockerfile" "web-frontend"
+
+backend-lint:
+  stage: lint
+  image: docker:19.03.12
+  services:
+    - docker:19.03.12-dind
+  script:
+    - docker run $CI_IMAGE_REPO/backend:$CI_COMMIT_SHORT_SHA lint
+
+backend-test:
+  stage: test
+  image: docker:19.03.12
+  services:
+    - docker:19.03.12-dind
+    - name: postgres:11.3
+      alias: db
+    - name: liminspace/mjml-tcpserver:0.10
+      alias: mjml
+  variables:
+    DOCKER_HOST: tcp://docker:2376
+    DOCKER_TLS_CERTDIR: "/certs"
+    DATABASE_USER: baserow
+    DATABASE_PASSWORD: baserow
+    DATABASE_NAME: baserow
+  script:
+    - docker run $CI_IMAGE_REPO/backend:$CI_COMMIT_SHORT_SHA test
+
+publish-baserow-images:
+  image: docker:19.03.12
+  stage: publish
   services:
     - docker:19.03.12-dind
   variables:
@@ -99,7 +176,6 @@ build-baserow-images:
     - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
   script:
     - |
-      IMAGE_REPO=$CI_REGISTRY_IMAGE/testing
       echo "Building and shipping image to $IMAGE_REPO"
       #Build date for opencontainers
       BUILDDATE="'$(date '+%FT%T%z' | sed -E -n 's/(\+[0-9]{2})([0-9]{2})$/\1:\2/p')'" #rfc 3339 date
@@ -107,23 +183,25 @@ build-baserow-images:
       #Add ref.name for opencontainers
       IMAGE_LABELS="$IMAGE_LABELS --label org.opencontainers.image.ref.name=$IMAGE_REPO:$CI_COMMIT_REF_NAME"
 
-      VERSIONLABEL=$CI_COMMIT_TAG
-      if [[ ! -z "$VERSIONLABEL" ]]; then
-        IMAGE_LABELS="$IMAGE_LABELS --label org.opencontainers.image.version=$VERSIONLABEL"
-        ADDITIONALTAGLIST="$ADDITIONALTAGLIST $VERSIONLABEL"
-      fi
-
       # Ensure we don't go over 128 char docker tag length limit
       TRUNCATED_BRANCH_NAME=${CI_COMMIT_REF_NAME:0:100}
       BRANCH_TAG=$TRUNCATED_BRANCH_NAME-$CI_COMMIT_SHORT_SHA
       LATEST_BRANCH_TAG=$TRUNCATED_BRANCH_NAME-latest
+
       ADDITIONALTAGLIST="$ADDITIONALTAGLIST $BRANCH_TAG $LATEST_BRANCH_TAG"
 
-      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then ADDITIONALTAGLIST="$ADDITIONALTAGLIST latest"; fi
+      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
+        ADDITIONALTAGLIST="$ADDITIONALTAGLIST latest";
+        VERSIONLABEL=$CI_COMMIT_TAG
+        if [[ ! -z "$VERSIONLABEL" ]]; then
+          IMAGE_LABELS="$IMAGE_LABELS --label org.opencontainers.image.version=$VERSIONLABEL"
+          ADDITIONALTAGLIST="$ADDITIONALTAGLIST $VERSIONLABEL"
+        fi
+      fi
       # todo put "develop" in some sort of project variable.
       if [[ "$CI_COMMIT_BRANCH" == "develop" ]]; then ADDITIONALTAGLIST="$ADDITIONALTAGLIST dev-latest"; fi
 
-      build_and_tag_image(){
+      build_and_push_image(){
         IMAGE_PATH=$1
         IMAGE_NAME=$2
 
@@ -136,79 +214,25 @@ build-baserow-images:
           for TAG in $ADDITIONALTAGLIST; do
             TAGGED_IMAGE=$IMAGE_REPO/$IMAGE_NAME:$TAG
             FORMATTEDTAGLIST="${FORMATTEDTAGLIST} -t $TAGGED_IMAGE ";
-            echo "$TAGGED_IMAGE\n" >> "image_tags_to_push_on_success.txt"
           done;
         fi
 
-        # Try cache from this branches latest image, if not fall back to the latest
-        # develop image.
-        CACHE_IMAGE="$IMAGE_REPO/$IMAGE_NAME:dev-$LATEST_BRANCH_TAG"
-        if ! docker pull $CACHE_IMAGE; then
-          CACHE_IMAGE="$IMAGE_REPO/$IMAGE_NAME:dev-latest";
-          if ! docker pull $CACHE_IMAGE; then
-             CACHE_IMAGE=""
-          fi
-        fi
-        if [[ -n "$CACHE_IMAGE" ]]; then
-          echo "Caching docker build from $CACHE_IMAGE";
-          CACHE_ARG="--cache-from $CACHE_IMAGE";
-        else
-          echo "Couldn't find image to cache build using"
-          CACHE_ARG=""
+        # Build the normal non-dev target image with all the tags and labels.
+        docker build --cache-from $CI_IMAGE_REPO/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA $FORMATTEDTAGLIST $IMAGE_LABELS_WITH_TITLE -f $IMAGE_PATH .;
+
+        # Push all the tags we just built above
+        if [[ -n "$ADDITIONALTAGLIST" ]]; then
+          for TAG in $ADDITIONALTAGLIST; do
+            TAGGED_IMAGE=$IMAGE_REPO/$IMAGE_NAME:$TAG
+            docker push $TAGGED_IMAGE
+          done;
         fi
 
-        echo "$IMAGE_REPO/$IMAGE_NAME:dev-$LATEST_BRANCH_TAG\n" >> "image_tags_to_push_on_success.txt"
-        docker build --build-arg BUILDKIT_INLINE_CACHE=1 $CACHE_ARG --target dev --tag dev-$LATEST_BRANCH_TAG --tag build-local-$IMAGE_NAME -f $IMAGE_PATH .;
-        # Build the normal image which will use cached layers already built in dev
-        # build above.
-        docker build $FORMATTEDTAGLIST $IMAGE_LABELS_WITH_TITLE -f $IMAGE_PATH .;
-
+        # Push the CI image as the latest dev image.
+        DEV_LATEST_TAG=$IMAGE_REPO/$IMAGE_NAME:dev-$LATEST_BRANCH_TAG
+        docker tag $CI_IMAGE_REPO/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA $DEV_LATEST_TAG
+        docker push $DEV_LATEST_TAG
       }
 
-      build_and_tag_image "$CI_PROJECT_DIR/backend/Dockerfile" "backend"
-      build_and_tag_image "$CI_PROJECT_DIR/web-frontend/Dockerfile" "web-frontend"
-  artifacts:
-    paths:
-      - image_tags_to_push_on_success.txt
-
-backend-lint:
-  stage: lint
-  image: build-local-backend
-  entrypoint: [""]
-  script:
-    - /baserow/backend/docker/docker-entrypoint.sh lint
-
-backend-test:
-  stage: test
-  image: build-local-backend
-  entrypoint: [""]
-  services:
-    - name: postgres:11.3
-      alias: db
-    - name: liminspace/mjml-tcpserver:0.10
-      alias: mjml
-  variables:
-    DATABASE_USER: baserow
-    DATABASE_PASSWORD: baserow
-    DATABASE_NAME: baserow
-  script:
-    - /baserow/backend/docker/docker-entrypoint.sh test
-
-push-baserow-images:
-  image: docker:19.03.12
-  stage: push
-  services:
-    - docker:19.03.12-dind
-  variables:
-    DOCKER_BUILDKIT: 1
-    DOCKER_HOST: tcp://docker:2376
-    DOCKER_TLS_CERTDIR: "/certs"
-  dependencies:
-    - build-baserow-images
-  before_script:
-    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
-  script:
-    - |
-      while read p; do
-        echo "docker push $p"
-      done < image_tags_to_push_on_success.txt
+      build_and_push_image "$CI_PROJECT_DIR/backend/Dockerfile" "backend"
+      build_and_push_image "$CI_PROJECT_DIR/web-frontend/Dockerfile" "web-frontend"
